# Generated by Django 3.1.7 on 2021-02-28 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('flavour_text', models.CharField(max_length=500)),
                ('attack_buff', models.IntegerField()),
                ('defense_buff', models.IntegerField()),
                ('hitpoints_buff', models.IntegerField()),
                ('energy_buff', models.IntegerField()),
                ('eating_effect', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('target_team', models.IntegerField(choices=[(1, 'Own'), (2, 'Other')])),
                ('target_num', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Team')])),
                ('damage_num', models.IntegerField()),
                ('defense_mod', models.IntegerField()),
                ('healing_num', models.IntegerField()),
                ('energy_cost', models.IntegerField()),
                ('category', models.IntegerField(choices=[(1, 'Offensive'), (2, 'Defensive'), (3, 'Healing')])),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('base_attack', models.IntegerField()),
                ('base_defense', models.IntegerField()),
                ('base_hitpoints', models.IntegerField()),
                ('base_energy', models.IntegerField()),
                ('base_skills', models.ManyToManyField(to='viv_pets.Skill')),
                ('egg', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='viv_pets.egg')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack_modifier', models.IntegerField()),
                ('defense_modifier', models.IntegerField()),
                ('hitpoints_modifier', models.IntegerField()),
                ('energy_modifier', models.IntegerField()),
                ('extra_skills', models.ManyToManyField(to='viv_pets.Skill')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viv_pets.species')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('gender', models.IntegerField(choices=[(1, 'Female'), (2, 'Male')])),
                ('hatched', models.BooleanField(default=True)),
                ('attack_modifier', models.IntegerField()),
                ('defense_modifier', models.IntegerField()),
                ('hitpoints_modifier', models.IntegerField()),
                ('energy_modifier', models.IntegerField()),
                ('extra_skills', models.ManyToManyField(to='viv_pets.Skill')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viv_pets.species')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viv_pets.variant')),
            ],
        ),
    ]
