# Generated by Django 3.1.4 on 2021-03-01 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viv_pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='attack_modifier',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 1, 23, 16, 41, 172308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='defense_modifier',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='pet',
            name='energy_modifier',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_skills',
            field=models.ManyToManyField(blank=True, db_column='extra_skills', to='viv_pets.Skill'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hitpoints_modifier',
            field=models.IntegerField(blank=True),
        ),
    ]
