# Generated by Django 3.1.7 on 2021-05-12 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viv_pets', '0003_auto_20210307_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 8, 32, 46, 700529, tzinfo=utc)),
        ),
    ]
