# Generated by Django 3.1.7 on 2021-05-12 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viv_pets', '0006_auto_20210512_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 9, 23, 59, 618110, tzinfo=utc)),
        ),
    ]
