# Generated by Django 3.1.7 on 2021-05-13 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viv_pets', '0008_auto_20210513_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 11, 32, 34, 33832, tzinfo=utc)),
        ),
    ]
