# Generated by Django 3.2.4 on 2021-06-30 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('viv_pets', '0013_auto_20210607_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 6, 30, 5, 55, 16, 11958, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=500, validators=[profanity.validators.validate_is_profane_nospace]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=15, validators=[profanity.validators.validate_is_profane_nospace]),
        ),
    ]
