# Generated by Django 3.1.4 on 2021-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='EMAIL_FIELD',
            field=models.EmailField(default='noemail@void.com', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
