# Generated by Django 3.1.4 on 2021-01-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210105_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='EMAIL_FIELD',
        ),
    ]
