# Generated by Django 3.1.4 on 2021-01-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_player_email_field'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='Display_Name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
