# Generated by Django 3.1.7 on 2021-02-28 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210109_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='Date of birth (mm/dd/yyyy)'),
        ),
    ]
