# Generated by Django 3.1.7 on 2021-06-06 19:42

from django.db import migrations, models
import django.utils.timezone
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210512_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth (mm/dd/yyyy)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=18, unique=True, validators=[profanity.validators.validate_is_profane]),
        ),
    ]
