# Generated by Django 3.1.7 on 2021-06-07 21:53

from django.db import migrations, models
import profanity.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210606_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=18, unique=True, validators=[profanity.validators.validate_is_profane_nospace]),
        ),
    ]
