# Generated by Django 3.1.7 on 2021-03-07 21:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vivPets', '0002_auto_20210301_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 3, 7, 21, 33, 52, 900929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='extra_skills',
            field=models.ManyToManyField(blank=True, db_column='extra_skills', null=True, to='vivPets.Skill'),
        ),
    ]
