# Generated by Django 3.1.7 on 2021-05-12 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vivPets', '0004_auto_20210512_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 12, 8, 34, 14, 375346, tzinfo=utc)),
        ),
    ]
