# Generated by Django 3.1.7 on 2021-05-13 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vivPets', '0009_auto_20210513_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='attack_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 5, 13, 11, 49, 32, 208395, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pet',
            name='defense_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='energy_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='hitpoints_modifier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
