# Generated by Django 3.1.7 on 2021-06-06 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vivPets', '0011_auto_20210513_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 6, 6, 19, 42, 47, 908028, tzinfo=utc)),
        ),
    ]
