# Generated by Django 3.1.7 on 2021-06-07 21:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vivPets', '0012_auto_20210606_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 6, 7, 21, 53, 29, 310827, tzinfo=utc)),
        ),
    ]
