# Generated by Django 3.1.7 on 2021-05-12 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vivPets', '0005_auto_20210512_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petLimit', models.IntegerField(default=2)),
                ('friendlyName', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=500)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('starredPet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vivPets.pet')),
            ],
        ),
    ]
